name: Build

on:
  push:
    # ignoring tags also ignores branches
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: windows-latest
    permissions:
      contents: read
    outputs:
      build: ${{ steps.filter.outputs.build }}
      code: ${{ steps.filter.outputs.code }}
    steps:
      - name: Checkout
        # v7
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        # v4
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d
        id: filter
        with:
          filters: |
            build:
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
            code:
              - 'src/**'
  build:
    name: Build
    runs-on: windows-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.build == 'true' || needs.check-changes.outputs.code == 'true' }}
    steps:
      - name: Checkout
        # v7
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup CMake
        # v4.4.2
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb
      - name: Run CMake
        # v10
        uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956
        with:
          configurePreset: release
          buildPreset: release
