name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  pre:
    runs-on: windows-latest
    outputs:
      # Assume pushes to tags are always full releases
      is_full_release: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' }}
    steps:
      - run: "true"
  release:
    name: Release
    needs: pre
    runs-on: windows-latest
    environment: publishing
    permissions:
      contents: write
    steps:
      - name: Checkout
        # v7
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup CMake
        # v4.4.2
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb
      - name: Run CMake
        # v10
        uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956
        with:
          configurePreset: release
          buildPreset: release
      - name: Generate Changelog
        if: needs.pre.outputs.is_full_release == 'true'
        id: cliff
        # v4
        uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff
        with:
          config: ".cliff.toml"
          args: --latest -v
        env:
          GITHUB_REPO: ${{ github.repository }}
      - name: Create GitHub Release
        if: needs.pre.outputs.is_full_release == 'true'
        # v3
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          fail_on_unmatched_files: true
          files: |
            build/release/native-*.dll
          body: ${{ steps.cliff.outputs.content }}
